language: julia
coveralls: true
os:
  - linux
  - osx 
  - windows
julia:
  - 1.0
  - 1
matrix:
  allow_failures:
    - julia: 1.0
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
after_success:
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("PACKAGE_NAME")); include(joinpath("docs", "make.jl"))'
